### ISSUE TITLE
Doesn't work for versions 4.x of reveal JS

### ISSUE THREAD

**Issue by kxygk** [asciidoctor/asciidoctorj-reveal.js#6]
I'm super new to this, so please forgive me if if this is an error on my part, but using the Java AsciidoctorJ API example (through Clojure)  the generated HTML autogenerated links to stuff like `reveal.js/css/reset.css`  and `reveal.js/css/reveal.css`. It looks like these files were moved/renamed in versions 4.x of Reveal.

Maybe the examples were updated without testing?

I changed the example code to link to a local copy I have at 3.9.2 and everything works properly

Thank you for this library. It's very handy. I can generate slides from asciidoc files right from the REPL

**Comment by robertpanzer** [comment]
Could you please provide a reproducer project?

**Comment by kxygk** [comment]
Sorry for the delay! 

I really didn't do anything crazy. I just ran the first example in the github `README.adoc`. If you've been able to run that without issue then something really wacky is going on :)

The issue is that I rewrote it all in Clojure.. so it's a bit tricky to give you an easily runnable example (unless you use Clojure yourself). I think it should be readable b/c I followed your general example. (sorry it's been like a decade since I've written any Java - I don't even know how to setup a project)

If you don't want to deal with this issue then I completely understand. Everyone is busy and I'm not giving a neat repro here

I have `reveal.js` cloned in a neighboring directory and I in effect modify its version with `git`. Hence why i point to it with `"../reveal.js"`

``` clojure
(use 'clojure.tools.deps.alpha.repl)

(add-libs
  {'org.asciidoctor/asciidoctorj-revealjs
   {:mvn/version
    "5.0.0.rc1"}
   'org.asciidoctor/asciidoctorj-pdf
   {:mvn/version
    "1.6.2"}
   'org.asciidoctor/asciidoctorj
   {:mvn/version
    "2.5.3"}
   })

(import [org.asciidoctor Asciidoctor OptionsBuilder SafeMode]) 

(let [filestr "/home/kxygk/Projects/stars/deepco2.adoc"
      input-file (clojure.java.io/file filestr)
      adoctor (org.asciidoctor.Asciidoctor$Factory/create)
      reveal-option (doto (org.asciidoctor.OptionsBuilder/options)
                      (.backend "revealjs")
                      (.safe org.asciidoctor.SafeMode/UNSAFE)
                      (.attributes (.attribute (org.asciidoctor.AttributesBuilder/attributes)
                                               "revealjsdir"
                                               "../reveal.js")))]
  (.requireLibrary adoctor
                   (into-array String
                               ["asciidoctor-revealjs"]))
  (.convertFile adoctor
                input-file
                reveal-option))
```

**Comment by robertpanzer** [comment]
I am not able to spontaneously run this progream.
But I just tried with the current asciidoctorj and the latest asciidoctorj-revealjs 5.0.0.rc1 and had no issues.
I cloned the current  reveal.js from https://github.com/hakimel/reveal.js to the parent directory saying in the package.json that I got version 4.3.1.
Then I unpacked that archive to ..  providing the directory revealjs-master.
After running the following command (with asciidoctorj-revealjs in the lib directory)
```
asciidoctorj -b revealjs -a revealjsdir=../reveal.js test.adoc
```
I got a test.html that successfully loaded the reveal.js stylesheets and javascript from the local filesystem, e.g. `reveal.js-master/dist/reveal.js`.
So you might want to check in the browser what paths it is trying to load.
This is how the element for loading the js for example looks like in the generated output:
```
<link rel="stylesheet" href="../reveal.js/dist/reveal.css">
```

**Comment by kxygk** [comment]
Oh jeez, I must have had a dirty dependency cache or something (my fault for using `add-libs` ..). After restarting Emacs and rerunning it outputs the correct HTML that works with 4.3.1. This is embarrassing. I'm really sorry for wasting your time. Thank you for verifying things on your end. I really appreciate it. And the work you put into this. It's very convenient
